---
- name: Shutodwn win
  hosts: all_win

  tasks:
  - name: Shutdown via Powershel
    ansible.windows.win_powershell:
      script: |
        shutdown /s
    become: yes
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: PRIM\witcher